--[[ require("user.barbar") ]]
require("user.plugins")
require("user.options")
require("user.keymaps")
require("user.colorscheme")
require("user.bufferline")
require("user.cmp")
require("user.lsp")
require("user.lspsaga")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.impatient")
require("user.indentline")
require("user.alpha")
require("user.whichkey")
require("user.autocommands")
--[[ require("user.neotest") ]]
